import PolicyLayout from '../components/PolicyLayout';

const sections = [
  {
    heading: 'Overview',
    content: (
      <>
        <p>
          At PromptX, we stand behind the quality of our prompts and want you to be completely satisfied with your purchase. This Refund Policy outlines when refunds are available, how to request one, and what to expect during the process.
        </p>
        <p>
          Please read this policy carefully before making a purchase. By completing a transaction on PromptX, you acknowledge that you have read and understood this Refund Policy.
        </p>
      </>
    ),
  },
  {
    heading: 'Digital Products — General Policy',
    content: (
      <>
        <p>
          PromptX sells <strong>digital products</strong> (AI prompts). Due to the nature of digital goods — which are delivered instantly and cannot be "returned" in the traditional sense — <strong>all sales are generally final and non-refundable</strong>.
        </p>
        <p>
          This is consistent with standard industry practice for digital content marketplaces. Once you have accessed the prompt content, it cannot be "un-delivered."
        </p>
        <p>
          We encourage you to take full advantage of our <strong>2 free prompts</strong> (no credit card required) to evaluate the quality and style of our content before upgrading to Pro.
        </p>
      </>
    ),
  },
  {
    heading: 'Exceptions — When Refunds Are Granted',
    content: (
      <>
        <p>
          We do make exceptions to our no-refund policy in the following circumstances:
        </p>
        <ul className="list-none space-y-3 mt-3">
          {[
            {
              label: 'Technical failure',
              desc: 'If a confirmed payment was charged but you were not granted Pro access within 24 hours due to a verified technical error on our end.',
            },
            {
              label: 'Duplicate charge',
              desc: 'If you were charged more than once for the same Pro membership due to a payment processing error.',
            },
            {
              label: 'Unauthorised transaction',
              desc: 'If you can demonstrate that the purchase was made without your authorisation and you notify us within 48 hours of the charge.',
            },
            {
              label: 'Platform-wide unavailability',
              desc: 'If the PromptX platform was completely inaccessible for more than 72 consecutive hours after your purchase, preventing you from accessing any prompts.',
            },
          ].map(({ label, desc }) => (
            <li key={label} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              <span><strong className="text-black">{label}:</strong> {desc}</span>
            </li>
          ))}
        </ul>
        <p className="mt-4 text-[13px] bg-gray-50 border border-gray-100 rounded-xl p-4 text-gray-500 leading-relaxed">
          <strong className="text-gray-700">Please note:</strong> Dissatisfaction with the output generated by third-party AI tools (Midjourney, DALL·E, Sora, etc.) does not constitute grounds for a refund. AI output quality depends on the tool version, your settings, and many factors outside our control.
        </p>
      </>
    ),
  },
  {
    heading: 'How to Request a Refund',
    content: (
      <>
        <p>
          If you believe you qualify for a refund under one of the exceptions above, please contact us as soon as possible with the following information:
        </p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Your registered email address.',
            'The date and approximate time of the purchase.',
            'Your Stripe payment confirmation or receipt number (available in your confirmation email).',
            'A clear description of the issue you experienced.',
            'Any relevant screenshots or error messages.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-4">
          Submit your request to:{' '}
          <a href="mailto:refunds@promptx.ai" className="text-black font-medium underline underline-offset-2">
            refunds@promptx.ai
          </a>
        </p>
        <p className="mt-2">
          Refund requests must be submitted within <strong>7 days</strong> of the original purchase date. Requests submitted after this window will not be considered.
        </p>
      </>
    ),
  },
  {
    heading: 'Refund Review Process',
    content: (
      <>
        <p>
          Once we receive your refund request, our team will:
        </p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Acknowledge receipt of your request within 1 business day.',
            'Review the details of your purchase and the issue described.',
            'Respond with a decision within 3–5 business days.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-3">
          We reserve the right to request additional information to verify your claim. Providing false or misleading information to obtain a refund may result in account suspension.
        </p>
      </>
    ),
  },
  {
    heading: 'Refund Processing Time',
    content: (
      <>
        <p>
          If your refund is approved, we will initiate the refund through Stripe to your original payment method. Processing times are as follows:
        </p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Credit / Debit cards: 5–10 business days depending on your bank.',
            'Digital wallets (Apple Pay, Google Pay): 3–7 business days.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-3">
          If your refund is approved, your Pro access will be revoked at the time the refund is initiated.
        </p>
      </>
    ),
  },
  {
    heading: 'Chargebacks',
    content: (
      <p>
        If you initiate a chargeback with your bank or card issuer without first contacting us to resolve the issue, we reserve the right to permanently suspend your account and contest the chargeback. We strongly encourage you to contact us first at{' '}
        <a href="mailto:refunds@promptx.ai" className="text-black font-medium underline underline-offset-2">
          refunds@promptx.ai
        </a>{' '}
        — most issues can be resolved quickly and without the delays a chargeback process involves.
      </p>
    ),
  },
  {
    heading: 'Changes to This Policy',
    content: (
      <p>
        We reserve the right to modify this Refund Policy at any time. Changes will be effective immediately upon posting to this page with an updated effective date. Your continued use of the Service after changes are posted constitutes your acceptance of the revised policy.
      </p>
    ),
  },
  {
    heading: 'Contact Us',
    content: (
      <p>
        For refund requests or questions about this policy, please email us at{' '}
        <a href="mailto:refunds@promptx.ai" className="text-black font-medium underline underline-offset-2">
          refunds@promptx.ai
        </a>
        . For general enquiries, reach us at{' '}
        <a href="mailto:hello@promptx.ai" className="text-black font-medium underline underline-offset-2">
          hello@promptx.ai
        </a>
        . We aim to respond to all messages within 1–2 business days.
      </p>
    ),
  },
];

export default function RefundPolicy() {
  return (
    <PolicyLayout
      title="Refund Policy"
      subtitle="Our commitment to fair and transparent refunds."
      effectiveDate="May 12, 2026"
      accentColor="#10b981"
      sections={sections}
    />
  );
}
