import PolicyLayout from '../components/PolicyLayout';

const sections = [
  {
    heading: 'Acceptance of Terms',
    content: (
      <>
        <p>
          By accessing or using the PromptX platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
        </p>
        <p>
          These Terms apply to all visitors, registered users, and others who access or use the Service. By creating an account or making a purchase, you confirm that you are at least 18 years of age, or that you are accessing the Service under the supervision of a parent or legal guardian who has agreed to these Terms.
        </p>
      </>
    ),
  },
  {
    heading: 'Description of Service',
    content: (
      <>
        <p>
          PromptX is a digital marketplace that sells curated AI prompts for use with third-party AI tools including, but not limited to, Midjourney, DALL·E, Stable Diffusion, Sora, Runway ML, and Claude. Prompts are textual instructions designed to guide AI systems in generating specific outputs.
        </p>
        <p>
          We offer a <strong>Pro membership</strong> for a one-time fee of <strong>$10 USD</strong>, which grants lifetime access to all prompts available on the platform at the time of purchase, as well as prompts added in the future.
        </p>
        <p>
          PromptX does not operate, own, or control any of the third-party AI tools referenced in our prompts. The results generated by those tools may vary based on their current model versions, your usage context, and other factors outside our control.
        </p>
      </>
    ),
  },
  {
    heading: 'Account Registration',
    content: (
      <>
        <p>
          To purchase prompts or access your Pro membership, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated.
        </p>
        <p>You are responsible for:</p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Maintaining the confidentiality of your account password.',
            'All activities that occur under your account.',
            'Notifying us immediately at legal@promptx.ai of any unauthorized use of your account.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-3">
          PromptX reserves the right to suspend or terminate accounts that we determine, in our sole discretion, to be in violation of these Terms.
        </p>
      </>
    ),
  },
  {
    heading: 'Purchases and Payment',
    content: (
      <>
        <p>
          All purchases on PromptX are processed through Stripe, a third-party payment processor. By making a purchase, you agree to Stripe's terms of service and privacy policy. We do not store your full card details on our servers.
        </p>
        <p>
          All prices are listed in US Dollars (USD). Applicable taxes may be added at checkout depending on your location. Once a purchase is confirmed, you will receive immediate access to your Pro membership.
        </p>
        <p>
          The Pro membership fee of $10 USD is a <strong>one-time, non-recurring charge</strong>. There are no hidden fees or automatic renewals associated with your purchase.
        </p>
      </>
    ),
  },
  {
    heading: 'License to Use Prompts',
    content: (
      <>
        <p>
          Upon purchase of a Pro membership, PromptX grants you a <strong>non-exclusive, non-transferable, worldwide license</strong> to use the prompts for both personal and commercial purposes, including:
        </p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Creating and selling AI-generated artwork, videos, or websites for clients.',
            'Using prompts in your own products, services, or marketing materials.',
            'Sharing the AI-generated output (not the prompt text itself) publicly.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-3">
          You may <strong>not</strong> resell, sublicense, redistribute, or share the prompt text itself — including posting prompts publicly, adding them to other marketplaces, or including them in products where others can extract the text.
        </p>
      </>
    ),
  },
  {
    heading: 'Intellectual Property',
    content: (
      <>
        <p>
          All prompts, content, branding, logos, and platform design on PromptX are the intellectual property of PromptX or its licensors and are protected by applicable copyright and intellectual property laws.
        </p>
        <p>
          Your purchase grants you a license to use the prompts as described in Section 5. It does not transfer ownership of the prompts to you. PromptX retains all rights, title, and interest in and to the prompts and all related intellectual property.
        </p>
      </>
    ),
  },
  {
    heading: 'Prohibited Uses',
    content: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'Resell, redistribute, or sublicense any prompt purchased on PromptX.',
            'Reverse engineer, scrape, or systematically extract content from the platform.',
            'Create competing products or services using our prompt content.',
            'Violate any applicable law or regulation.',
            'Engage in fraud, misrepresentation, or any abusive behavior.',
            'Use our prompts to generate content that is illegal, harmful, or defamatory.',
            'Attempt to gain unauthorized access to our systems or other users\' accounts.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    heading: 'Disclaimer of Warranties',
    content: (
      <>
        <p>
          The Service is provided on an <strong>"as is"</strong> and <strong>"as available"</strong> basis without warranties of any kind, either express or implied. PromptX does not warrant that:
        </p>
        <ul className="list-none space-y-2 mt-2">
          {[
            'The prompts will produce specific or guaranteed results in any AI tool.',
            'The Service will be uninterrupted, error-free, or secure.',
            'The AI tools referenced will continue to support the prompts as provided.',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-gray-300" />
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-3">
          AI models are updated frequently by their respective providers and results may differ from any preview images shown on our platform.
        </p>
      </>
    ),
  },
  {
    heading: 'Limitation of Liability',
    content: (
      <p>
        To the maximum extent permitted by law, PromptX shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, lost revenue, lost data, or business interruption, arising out of your use of or inability to use the Service. Our total liability to you for any claim arising from these Terms or the Service shall not exceed the amount you paid to PromptX in the twelve (12) months preceding the claim.
      </p>
    ),
  },
  {
    heading: 'Changes to Terms',
    content: (
      <>
        <p>
          We reserve the right to modify these Terms at any time. When we make material changes, we will update the effective date at the top of this page. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms.
        </p>
        <p>
          We encourage you to review these Terms periodically. If you disagree with the updated Terms, your sole remedy is to discontinue using the Service.
        </p>
      </>
    ),
  },
  {
    heading: 'Governing Law',
    content: (
      <p>
        These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which PromptX operates, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved through binding arbitration or in the courts of competent jurisdiction.
      </p>
    ),
  },
  {
    heading: 'Contact Us',
    content: (
      <p>
        If you have any questions about these Terms of Service, please contact us at{' '}
        <a href="mailto:legal@promptx.ai" className="text-black font-medium underline underline-offset-2">
          legal@promptx.ai
        </a>
        . We aim to respond to all inquiries within 2 business days.
      </p>
    ),
  },
];

export default function TermsOfService() {
  return (
    <PolicyLayout
      title="Terms of Service"
      subtitle="Please read these terms carefully before using PromptX."
      effectiveDate="May 12, 2026"
      accentColor="#6366f1"
      sections={sections}
    />
  );
}
